language: go
go:
  - 1.2

install:
  - export GOBIN=`pwd`
  - go get -d -v -t ./...
  - go build -v ./...
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ls
  - ls ..
  - go test
  - ./ginkgo -r