language: go
go:
  - 1.2

install:
  - mkdir TEMP_EXE
  - export GOBIN=`pwd`/TEMP_EXE
  - export PATH=$PATH:$GOBIN
  - go get -d -v -t ./...
  - go build -v ./...
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r